### Example
## Input
# input rgba image path (default to None, can be load in GUI too)
input: 
# # scene_prompt
# scene: 'A bedroom with a bed, two wooden nightstands, a square wooden table with a table lamp on it, and a wooden wardrobe'
# # input text prompt (default to None, can be input in GUI too)
# prompt: ['A table lamp',
# 'A square wooden dining table is supported by four solid legs',
# 'A bed',
# 'A compact wooden nightstand with two drawers',
# 'A compact wooden nightstand with two drawers',
# 'A wooden wardrobe with double doors']
# # floor prompt
# floor: ['light-colored wood floor']
# # input object center
# center: [[0.45, 0.375, 0.7], [0.45, 0.15, 0.7], [-0.55, 0.2, 0], [-0.75, 0.15, 0.5], [-0.75, 0.15, -0.5], [0.3, 0.2, -0.7]]
# # input object edge
# edge: [[0.1, 0.15, 0.1], [0.3, 0.3, 0.3], [0.7, 0.4, 0.5], [0.2, 0.3, 0.25], [0.2, 0.3, 0.25], [0.4, 0.4, 0.2]]
# # orientation
# ori: [0, 0, 0, 0, 0, 180]

# scene: 'A panda is sitting on a chair with two armrests'
# prompt: ['A panda with mouth open, one hand on the armrest and the other on its leg is sitting', 'A chair with two armrests']

# floor: ['light-colored wood floor']

# center: [[0.0, 0.6, 0.0], [0.0, 0.2, 0.0]]

# edge: [[0.5, 0.8, 0.5], [0.6, 0.4, 0.6]]

# ori: [0, 0]

scene: 'The black and white cat is wearing shades with a pink border'
prompt: ['The black and white cat is wearing shades with a pink border']

floor: ['light-colored wood floor']

center: [[0.0, 0.3, 0.0]]

edge: [[0.8, 0.6, 0.6]]

ori: [0]

# scene: 'A realistic man in brown trousers, black trench coat and red t-shirt, and the man is waving'  # 把 不同的 part 顺序调整一下，看看效果
# prompt: ['A realistic man is waving', 'brown trousers', 'black trench coat', 'red t-shirt']

# floor: ['light-colored wood floor']

# center: [[0.0, 0.4, 0.0]]

# edge: [[0.4, 0.8, 0.4]]

# ori: [0, 0, 0, 0]

# scene: 'A man is sitting on a chair with two armrests'
# prompt: ['A man with mouth open, one hand on the armrest and the other on its leg', 'A chair with two armrests']

# floor: ['light-colored wood floor']

# center: [[0.0, 0.7, 0.0], [0.0, 0.3, 0.0]]

# edge: [[0.4, 0.6, 0.4], [0.6, 0.6, 0.6]]

# ori: [0, 0]

# scene: 'A panda is wearing a pair of sunglasses'
# prompt: ['A panda with mouth open wearing a pair of sunglasses']

# floor: ['light-colored wood floor']

# center: [[0.0, 0.4, 0.0]]

# edge: [[0.6, 0.8, 0.6]]

# ori: [0]

# layout scale
layout_scale: 1
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: -20
# reference image resolution
ref_size: 256
# density thresh for mesh extraction
density_thresh: 1
# floor point scale
floor_scale: 0.02

load_object:

### Output
# outdir: bedroom
# save_path: bedroom

outdir: cat_0920_2
save_path: cat_0920_2

### Training
# enable overlap reg loss
overlap: True
# enable layout loss
layout: True
# enable scale loss
regloss: True
# guidance loss weights (0 to disable)
lambda_sd: 1
mvdream: True
lambda_zero123: 0
# training iterations
iters: 20000
# iters: 15000
# training camera radius
radius: 3
# training camera fovy
fovy: 49.1
# checkpoint to load (should be a ply file)
load:
# prob to invert background color during training (1 = always black, 0 = always white)
invert_bg_prob: 0.5
# interval for ControlNet
interval: 6

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Gaussian splatting
# num_pts: 100000
num_pts: 120000
sh_degree: 0
position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
# position_lr_max_steps: 30000
position_lr_max_steps: 30000
feature_lr: 0.005
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.001

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2